version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: maya-inventory-manager
    ports:
      - "8437:3000"
    environment:
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
    restart: unless-stopped 